### ISSUE TITLE
Android Compose Change the App Icon

### ISSUE THREAD

**Issue by bkrauth** [google-developer-training/basic-android-kotlin-compose-training-affirmations#24] opened 2022-11-22 20:27 UTC
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-training-change-app-icon#3

**Describe the problem**
A clear and concise description of what the problem is.
Text says  "drawable-v26 > ic_launcher_foreground.xml"
Actual directory installed is "drawable-v24 ..."

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Lesson 4, step 4

**How to reproduce?**
What are the exact steps to reproduce the problem?
Reading Text.
Downloaded files from Git as instructed at beginning of prior lesson

**Versions**
1. What version of Android Studio are you using?  2021.3.1 Patch 1
2. What API level are you targeting?  31

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by osuleymanova** [comment] 2022-11-30 18:49
Duplicate of #19

**Comment by sc-gds-lxl** [comment] 2023-03-08 21:46
Fixed

**Closed by sc-gds-lxl** 2023-03-08 21:46 UTC
