### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by Radami** [google-developer-training/basic-android-kotlin-compose-training-affirmations#22] opened 2022-11-21 06:38 UTC
**Generics, objects, and extensions**

**Describe the problem**
Chapter 7 has a wrong println output

**In which lesson and step of the codelab can this issue be found?**
7 -> Replace long object names using let() -> 6

**How to reproduce?**
The text is static

**Versions**
N/A

**Additional information**
The correct answer is:

Quoth the raven ___
nevermore
MEDIUM

The sky is green. True or false
false
EASY

How many days are there between full moons?
28
HARD

**codelab:** basic-android-kotlin-compose-generics

**Comment by osuleymanova** [comment] 2022-12-01 00:11
Duplicate of #20

**Comment by osuleymanova** [comment] 2022-12-05 20:56
Hello @Radami,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screen Shot 2022-12-05 at 12 53 00 PM](https://user-images.githubusercontent.com/86437155/205741129-9c848463-ca07-49c1-948f-c8453a338f8b.png)

**Closed by osuleymanova** 2022-12-05 20:56 UTC
