### ISSUE TITLE
Android Compose Change the App Icon

### ISSUE THREAD

**Issue by ParkSangYeol** [google-developer-training/basic-android-kotlin-compose-training-affirmations#27] opened 2022-11-28 08:28 UTC
**Name of the Codelab or Codelab URL**

https://developer.android.com/codelabs/basic-android-kotlin-compose-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-training-change-app-icon#5

**Describe the problem**
A clear and concise description of what the problem is.

The image of foreground file provided by codelab is different from the preview of codelab.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

Android Basics with Compose 
Unit 3: Display lists and use Material Design 
Pathway 2: Build a scrollable list 
Change the icon codelab 
step 6: Change the app icon

**How to reproduce?**
What are the exact steps to reproduce the problem?

I think the foreground file should be changed or preview should be changed.

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

![image](https://user-images.githubusercontent.com/70800808/204228410-d7667427-b496-4036-bb6c-a5b674fbe74f.png)

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by osuleymanova** [comment] 2022-11-30 18:44
Duplicate of #25

**Comment by sc-gds-lxl** [comment] 2023-02-28 03:23
Closing as duplicate.

**Closed by sc-gds-lxl** 2023-02-28 03:23 UTC
